package lisa.maths.SetTheory.Types.ADTv2.support.semantics

import lisa.maths.SetTheory.SetTheory.{*, given}
import lisa.maths.Quantifiers.{existsOneEpsilon, existsOneEpsilonUniqueness}
import lisa.maths.SetTheory.Types.ADTv2.support.core.Utils.*
import lisa.utils.prooflib.BasicStepTactic.Restate
import lisa.utils.prooflib.BasicStepTactic.RightForall

/**
 * Helpers for named semantic symbols in ADTv2.
 *
 * The classes in this file factor the common pattern of introducing polymorphic
 * `DEF`-backed symbols, and then optionally strengthening them when the body is an
 * epsilon-selected witness of a uniquely characterized object.
 *
 * The hierarchy has three layers:
 *   - [[DefinedSymbol]] for raw definitional packaging
 *   - [[UniqueDefinedSymbol]] for `term := ε(x, Def(x))` plus `Def(term)`
 *   - [[UniqueCharacterizedSymbol]] for the full theorem
 *     `forall(x, term = x <-> Def(x))`
 */

/**
 * Plain parameterized `DEF`-backed symbol.
 *
 * This is the base layer of the hierarchy. It packages the boilerplate shared by semantic
 * objects represented as named class functions over schematic parameters.
 *
 * It is purely definitional: it creates the underlying `DEF` symbol and exposes:
 *   - [[symbol]]: the raw constant
 *   - [[definition]]: the definitional equality generated by `DEF`
 *   - [[id]]: the identifier of the constant
 *   - [[term(args)]] / [[term]]: instantiated views of the symbol
 */
class DefinedSymbol(
    protected val name: String,
    protected val parametersSeq: Seq[Variable[Ind]],
    protected val body: Expr[Ind]
) {

  protected val classFunction: Constant[?] = {
    val classFunctionExpr: Expr[?] = lisa.utils.fol.FOL.Abs.apply(
      xs = parametersSeq,
      t = body
    )
    type S
    given lisa.utils.fol.FOL.IsSort[S] =
      lisa.utils.fol.FOL.unsafeSortEvidence(classFunctionExpr.sort)
    DEF(using name = name)(classFunctionExpr.asInstanceOf[Expr[S]])
  }
  classFunction.printAs(args => renderAppliedSymbol(name, parametersSeq.size, args))

  val symbol: Constant[?] = classFunction
  val definition: JUSTIFICATION = classFunction.definition
  val id: Identifier = classFunction.id

  def term(args: Seq[Expr[Ind]]): Expr[Ind] = (classFunction #@@ args).asInstanceOf[Expr[Ind]]

  val term: Expr[Ind] = term(parametersSeq)
}

/**
 * Epsilon-selected parameterized symbol obtained from a unique-existence theorem.
 *
 * This is the middle layer of the hierarchy. It extends [[DefinedSymbol]] with the common
 * ADTv2 pattern
 *
 * `term := ε(x, Def(x))`
 *
 * where a theorem of the form `existsOne(x, Def(x))` is already available.
 *
 * Besides the raw `DEF` symbol, it derives:
 *   - [[definitionFact]]: the theorem `Def(term)`
 *
 * This class is appropriate when downstream code only needs to know that the selected term
 * satisfies the defining predicate, but does not need the full extensional
 * characterization.
 */
class UniqueDefinedSymbol(
    override protected val name: String,
    protected val typeVariablesSeq: Seq[Variable[Ind]],
    protected val witnessVar: Variable[Ind],
    protected val definitionAt: Expr[Ind] => Expr[Prop]
)(
    protected val uniqueness: THM
) extends DefinedSymbol(
      name = name,
      parametersSeq = typeVariablesSeq,
      body = ε(witnessVar, definitionAt(witnessVar))
    ) {

  protected val witnessDefinition: Expr[Prop] = definitionAt(witnessVar)

  protected val classTermIsEpsilon: THM = Lemma(term === ε(witnessVar, witnessDefinition)) {
    have(thesis) by Congruence.from(definition)
  }

  val definitionFact: THM = Lemma(definitionAt(term)) {
    val epsilonWitness = ε(witnessVar, witnessDefinition)

    val definitionAtEpsilon = have(definitionAt(epsilonWitness)) by Tautology.from(
      uniqueness,
      existsOneEpsilon of (x := witnessVar, P := λ(witnessVar, witnessDefinition))
    )
    val epsilonEqTerm = have(epsilonWitness === term) by Congruence.from(classTermIsEpsilon)

    val definitionAtEpsilonWithEq =
      have((epsilonWitness === term) |- definitionAt(epsilonWitness)) by
        Weakening(definitionAtEpsilon)

    val replacementVar = variable[Ind]
    val definitionAtTerm =
      have((epsilonWitness === term) |- definitionAt(term)) by
        RightSubstEq.withParameters(
          List((epsilonWitness, term)),
          (Seq(replacementVar), definitionAt(replacementVar))
        )(definitionAtEpsilonWithEq)

    have(thesis) by Tautology.from(epsilonEqTerm, definitionAtTerm)
  }
}

/**
 * Uniquely characterized parameterized symbol.
 *
 * This is the strongest layer of the hierarchy. In addition to everything provided by
 * [[UniqueDefinedSymbol]], it proves the full characterization theorem:
 *
 * `forall(x, term = x <-> Def(x))`
 *
 * This is the right abstraction when later proofs need to instantiate the characterization
 * at `term` and extract typing facts, equations, or uniqueness consequences from it.
 */
final class UniqueCharacterizedSymbol(
    name: String,
    typeVariablesSeq: Seq[Variable[Ind]],
    witnessVar: Variable[Ind],
    definitionAt: Expr[Ind] => Expr[Prop]
)(
    uniqueness: THM
) extends UniqueDefinedSymbol(name, typeVariablesSeq, witnessVar, definitionAt)(uniqueness) {

  val characterization: THM =
    Lemma(forall(witnessVar, (term === witnessVar) <=> witnessDefinition)) {
      val epsilonWitness = ε(witnessVar, witnessDefinition)

      val epsilonCharacterization = have(
        witnessDefinition <=> (witnessVar === epsilonWitness)
      ) by Tautology.from(
        uniqueness,
        existsOneEpsilonUniqueness of (
          x := witnessVar,
          y := witnessVar,
          P := λ(witnessVar, witnessDefinition)
        )
      )

      val classTermIsEps = have(term === epsilonWitness) by
        Congruence.from(definition)

      val toRight = have((term === witnessVar) ==> (witnessVar === epsilonWitness)) subproof {
        assume(term === witnessVar)
        val termEqWitness = have(term === witnessVar) by Hypothesis
        val termEqEpsilon = have(term === epsilonWitness) by Tautology.from(classTermIsEps)
        have(witnessVar === epsilonWitness) by Congruence.from(termEqWitness, termEqEpsilon)
        thenHave(thesis) by Restate
      }

      val toLeft = have((witnessVar === epsilonWitness) ==> (term === witnessVar)) subproof {
        assume(witnessVar === epsilonWitness)
        val witnessEqEpsilon = have(witnessVar === epsilonWitness) by Hypothesis
        val termEqEpsilon = have(term === epsilonWitness) by Tautology.from(classTermIsEps)
        have(term === witnessVar) by Congruence.from(termEqEpsilon, witnessEqEpsilon)
        thenHave(thesis) by Restate
      }

      val equalityRewriting = have((term === witnessVar) <=> (witnessVar === epsilonWitness)) by
        Tautology.from(toRight, toLeft)

      have((term === witnessVar) <=> witnessDefinition) by
        Tautology.from(equalityRewriting, epsilonCharacterization)

      thenHave(thesis) by RightForall
    }

}
